Initial RMA extension commit
scandiweb-extensions/spwa-rma pull request #1
Opened 2021-10-21 09:29 UTC by SHADOWZXCV

2021-10-21 10:23 UTC, GAkim requested changes

2021-10-21 10:23 UTC, GAkim commented on app/code/ScandiPWA/RmaGraphQl/README.md
> +3. Compile the theme (`npm ci` && `npm run build` or `npm run watch`)
i thinks is irrelevant and confusing point for ScandiPWAv5

2021-10-21 10:23 UTC, GAkim commented on app/code/ScandiPWA/RmaGraphQl/etc/graphql/di.xml
> +</config>
missing blank line at the end of file

2021-10-21 10:23 UTC, GAkim commented on app/code/ScandiPWA/RmaGraphQl/package-lock.json
> +{
can't see a need in this file as it s just m2 Module

2021-10-21 10:23 UTC, GAkim commented on app/code/ScandiPWA/RmaGraphQl/package.json
> +{
can't see a need in this file as it s just m2 Module

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountMyReturns/MyAccountMyReturns.component.js
> +        // FIX: Array -> array
not useful comment

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountMyReturns/MyAccountMyReturns.component.js
> +    handleDropdownChange = (id) => {
PWA component are meant to be for render methods handle methods should be stored in container

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountMyReturns/MyAccountMyReturns.component.js
> +    handleReturnClick = () => {
PWA component are meant to be for render methods handle methods should be stored in container

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountMyReturns/MyAccountMyReturns.container.js
> +// FIX: from import {OrderDispatcher} from 'Store/Order/'; TO : import OrderDispatcher from 'Store/Order/Order.dispatcher';
useful comment

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountMyReturns/MyAccountMyReturns.container.js
> +// FIX: from 'Store/Navigation/'; TO : from 'Store/Navigation/Navigation.action';
useful comment

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountMyReturns/MyAccountMyReturns.container.js
> +        this.chosenOrderId = id;
too bad to mutate props, please if it possible use state

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountMyReturnsDropdown/MyAccountMyReturnsDropdown.component.js
> +        console.log('!!!', selectOptions);
Console log

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturn/MyAccountNewReturn.component.js
> +    handleSelectedItemsChange = (selectedItems) => {
handle methods to containers

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturn/MyAccountNewReturn.component.js
> +    handleRequestSubmitPress = async () => {
handle methods to containers

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturn/MyAccountNewReturn.component.js
> +    handleBackPress = () => {
handle methods to containers

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturn/MyAccountNewReturn.component.js
> +    handleTextAreaChange = (value) => {
handle methods to containers

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturn/MyAccountNewReturn.component.js
> +    isButtonEnabled() {
is methods to containers and with state change

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturn/MyAccountNewReturn.container.js
> +// FIX: {OrderQuery} to individual
useless comment

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturn/MyAccountNewReturn.container.js
> +// FIX: from 'Store/Notification/'; TO : from 'Store/Notification/Notification.action';
useless comment

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturn/MyAccountNewReturn.container.js
> +// FIX: from 'Store/Order/'; TO : from 'Store/Order/Order.dispatcher';
useless comment

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturn/MyAccountNewReturn.style.scss
> +        //  FIX: before-desktop -> mobile
useless comment

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturn/MyAccountNewReturn.style.scss
> +        //  FIX: before-desktop -> mobile
useless comment

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturn/MyAccountNewReturn.style.scss
> +
useless comment

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturn/MyAccountNewReturn.style.scss
> +        @include mobile {
something wring with indent

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturn/MyAccountNewReturn.style.scss
> +        @include mobile {
something wring with indent

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturn/MyAccountNewReturn.style.scss
> +        //  FIX: before-desktop -> mobile
comment

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturn/MyAccountNewReturn.style.scss
> +            //  FIX: before-desktop -> mobile
comment

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturnItemSelect/MyAccountNewReturnItemSelect.component.js
> +// FIX: from .omit to /omit
comment

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturnItemSelect/MyAccountNewReturnItemSelect.component.js
> +    handleItemSelect = (isChecked, id) => {
handle methods to container

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturnItemSelect/MyAccountNewReturnItemSelect.component.js
> +    handleReasonBlockSelect(blockId, key, id) {
handle methods to container

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturnItemSelect/MyAccountNewReturnItemSelect.component.js
> +    handleQtyChange(qty, id) {
handle methods to container

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountNewReturnItemSelect/MyAccountNewReturnItemSelect.style.scss
> +        //  FIX: before-desktop -> mobile
please remove this  // FIX comments every where!!!

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountReturnDetailsChat/MyAccountReturnDetailsChat.component.js
> +    onKeyEnterDown = (event) => {
i think this method also can be moved to contauiner

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountReturnDetailsChatMessages/MyAccountReturnDetailsChatMessages.component.js
> +    scrollToBottom() {
useRef please

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/component/MyAccountReturnDetailsItems/MyAccountReturnDetailsItems.style.scss
> +        @include mobile {
something wrong with indent

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/plugin/component/CmsBlock/CmsBlockContainer.plugin.js
> +const injectReturnsLinkIntoFooterLinks = (item) => {
why you just can't plugin in the footer and add your link in there after or before footer links block

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/plugin/component/MyAccountMyOrders/MyAccountMyOrdersComponent.plugin.js
> +            <tr>
can't see // adds return header to the table

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/plugin/component/Footer/FooterComponent.plugin.js
> +                    { COLUMN_MAP.map(instance.renderColumn) }
so you compleatly override footer columns, NOPE just add what you need

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/plugin/route/MyAccountContainer.plugin.js
> +    //     console.log('!!!', args, callback);
useless coments

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/styles/ordersAndReturnsWidget.scss
> +    display: none;
blank line after

2021-10-21 10:23 UTC, GAkim commented on pwa/packages/spwa-rma/src/styles/ordersAndReturnsWidget.scss
> +}
blank line at the end of the file

2021-10-22 06:05 UTC, SHADOWZXCV commented on pwa/packages/spwa-rma/src/plugin/component/CmsBlock/CmsBlockContainer.plugin.js
> +const injectReturnsLinkIntoFooterLinks = (item) => {
Maybe, but it will be a link outside of the footer component, and with different resolutions, it would not be perfectly placed as it is now?

2021-10-22 09:15 UTC, GAkim requested changes

2021-10-22 09:15 UTC, GAkim commented on .env
> +GRAPHQL_EXTENSION_FOLDER_NAME=../ScandiPWA/RmaGraphQl
Add please blank line at the end of the file

2021-10-22 09:25 UTC, GAkim approved these changes

2021-11-23 09:47 UTC, merged